// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckcymeagvuvumvrwirxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrY3ltZWFndnV2dW12cndpcnh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3MTI1NjIsImV4cCI6MjA4OTI4ODU2Mn0.aYZjjmwOb_u2Y10-4iSvOUiQKTaYMsFk5RhulQovi6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});